name: Daily Python Script

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every week at sunday midnight UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r ./.github/workflows/requirements.txt
      - name: Run script
        run: python ./.github/workflows/run.py
